### PR TITLE
Add ASUP and NMSDK API tracking for cookbook usage

### PR DESCRIPTION
**Pull request by bobcallaway**
This change adds tracking of the Chef module into the Data ONTAP system
so we can monitor adoption.

### CODE REVIEW

**Comment by mattray** [comment]
If my understanding of this is correct, we're adding a call-home feature by default for the cookbook? I think this should be documented and managed by an attribute to enable/disable as the user sees fit.

**Comment by bobcallaway** [comment]
The actual call home is configured on the required proxy software. If that's not on then this call is a no-op.

Bob Callaway, PhD
Principal Architect & Sr. Manager, Technical Marketing
Data Fabric Group

NetApp
919.476.8268<tel:919.476.8268> Direct Phone
919.601.1526<tel:919.601.1526> Mobile Phone
bob.callaway@netapp.com<mailto:bob.callaway@netapp.com>




On Wed, Aug 5, 2015 at 2:07 PM -0700, "Matt Ray" <notifications@github.com<mailto:notifications@github.com>> wrote:


If my understanding of this is correct, we're adding a call-home feature by default for the cookbook? I think this should be documented and managed by an attribute to enable/disable as the user sees fit.

-

**Comment by bobcallaway** [comment]
@mattray take a look at this and see if it is closer to what you had in mind. Given that there is the ultimate setting on the storage system itself, I think the default of `true` is sane.

**Comment by adamleff** [comment]
While I feel the community would normally desire to have any call-home feature disabled by default, given that a control is also available to users on the storage system, I think we can merge this. :smile: 

I will merge, tag, and push a release up to the supermarket.  Thanks for your PR!

**Comment by adamleff** [comment]
Version 0.3.0 of the cookbook has been pushed to the supermarket!  Thanks again.

**Pull request merged**
